name: PSScriptAnalyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  test scripts:
    runs-on: windows-latest
    name: PSScriptAnalyzer
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\
          recurse: true 
          output: results.sarif
